name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main # Executa quando há mudanças no branch principal

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Configurar o GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build # Ajuste se seu diretório de saída for diferente, como 'dist' ou algo personalizado

    - name: Publicar no GitHub Pages
      uses: actions/deploy-pages@v4
